name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "__tests__/**"
      - "tsconfig.json"
      - "package.json"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "__tests__/**"
      - "tsconfig.json"
      - "package.json"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          check-latest: true
          cache: "yarn"
      - run: yarn install
      - run: yarn test
